name: CI
on:
    push:
        branches: [ master ]
    
jobs:
    deploy:
        runs-on: self-hosted
    
    strategy: 
        matrix:
            node-version: [12.x]
            
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
            
   - name: npm test
     run: npm install
     
   - name: build
     run: docker build -t . latest
      
   - name: container
     run: dcker run latest
