

name: 30-oct-nodejs
on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build

 
      - name: test
        run: npm install
    
      - name: build
        run: docker build latest .
    
      - name: container 
        run: docker run latest
    
        
    
