
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: subdir/package-lock.json
    - run: npm install
    - run: npm test
        
    - name: test
      run: npm install
    
    - name: build
      run: docker build -latest .
    
    - name: container 
      run: docker run latest
    
        
    
